version: "3"

dotenv: ['.env']

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"

includes:
  local: .taskfiles/local.yaml
  lint: .taskfiles/lint.yaml
  test: .taskfiles/test.yaml

tasks:
  default:
    silent: true
    cmds: ["task -l"]