---
name: Lint
description: Lint Python code

inputs:
  python_version:
    description: Version of python to install
    required: false
    default: '3.10'

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        cache: pip
        python_version: ${{ inputs.python_version }}
      
    - name: Run Ruff
      run: |
        python -m pip install -U ruff
        python -m ruff check .
        python -m ruff format --check
      working-directory: .
      shell: bash