---
name: On Release

on:
  push:
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint

  release-image:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          push: "true"
          latest: "true"